apiVersion: apps/v1
kind: Deployment
metadata:
  name: __APP_NAME__
spec:
  selector:
    matchLabels:
      run: __APP_NAME__
  replicas: 1
  template:
    metadata:
      labels:
        run: __APP_NAME__
    spec:
      containers:
      - name: __APP_NAME__
        image: __IMAGE__
        ports:
        - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: __APP_NAME__
  labels:
    run: __APP_NAME__
spec:
  ports:
  - port: 9080
    protocol: TCP
    targetPort: 9080
  type: ClusterIP
  selector:
    run: __APP_NAME__
